name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via Vercel
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
